### ISSUE TITLE
Implement Custom Theme

### ISSUE THREAD

**Issue by ericsaupe** [railsgarage/adornit#1]

**Comment by thogg4** [comment]
@n00b2pr0 are you willing to do the work on this?

**Comment by n00b2pr0** [comment]
I bought the theme a few days ago and I can do some work on it. Hoping it will integrate easily.

**Comment by ericsaupe** [comment]
@n00b2pr0 is this the work being done in #16?

**Comment by n00b2pr0** [comment]
@ericsaupe Yeah it's started there. Theme assets are pulling in, but there will be a bit of effort to get the custom markup in, likely using deface. Had trouble getting the deface dsl working last week.

**Comment by thogg4** [comment]
fixed in #16
