### ISSUE TITLE
Wholesale Users

### ISSUE THREAD

**Issue by ericsaupe** [railsgarage/adornit#2]
Users should be flagged as Wholesale and see wholesale prices.

**Comment by ericsaupe** [comment]
@thogg4 how do I do a `bundle install` with spree-base?

**Comment by thogg4** [comment]
@ericsaupe you don't

**Comment by ericsaupe** [comment]
Haha how do I install new gems?

**Comment by ericsaupe** [comment]
![screen shot 2015-04-10 at 9 49 35 am](https://cloud.githubusercontent.com/assets/5138892/7091448/edd265ee-df66-11e4-98bb-376226ed5fb1.png)
