### ISSUE TITLE
Complex Shipping Rates

### ISSUE THREAD

**Issue by ericsaupe** [railsgarage/adornit#4]
Setup complex rates and rules

https://guides.spreecommerce.com/developer/shipments.html

**Comment by ericsaupe** [comment]
@n00b2pr0 do you have more information on this? I'd like to take it and see if there are extensions for it or if it just needs some Spree configuring I can do that too.

**Comment by n00b2pr0** [comment]
@ericsaupe Not a lot. I'll need to find out what data they have already for size and weight, and how they hope to price things.

**Comment by ericsaupe** [comment]
Sounds good. What I'll need to set things up right will be their stock location and whatever shipping services they use to ship their stuff.

**Comment by thogg4** [comment]
@ericsaupe is this done?

**Comment by ericsaupe** [comment]
We were waiting on the list of shipping methods and rates from AdornIt

**Comment by thogg4** [comment]
@ericsaupe oh cool. @n00b2pr0 any news on those?
